# Generated by Django 4.1.7 on 2023-03-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Adult', 'Adult'), ('VIP', 'VIP')], max_length=10),
        ),
    ]
